-- ════════════════════════════════════════════════════════════════
-- OBSOLETO — NO CORRER.
--
-- Este script intentaba reusar el nombre de columna `turno`, pero
-- esa columna YA EXISTÍA en `personal` con otro significado (AM/PM,
-- usada en las 43 filas de todas las áreas). Chocaba con esos datos
-- ("check constraint personal_turno_check is violated by some row").
--
-- Usar en su lugar: sql/personal_turno_produccion_v1.sql
-- (columna nueva `turno_produccion`, sin conflicto).
-- ════════════════════════════════════════════════════════════════
